// console.log("hello world")
// console.log(global)

// const os  = require('os')
// const path = require('path')
// console.log(os.version())
// console.log(os.type())
// console.log(os.homedir())
// console.log(__dirname)
// console.log(__filename)

// console.log(path.extname(__filename))
// console.log(path.basename(__filename))
// console.log(path.dirname(__filename))
// console.log(path.parse(__filename))

const {add, sub, multply,div} = require('../Math')
console.log(add(1,2))
console.log(sub(1,2))
console.log(div(1,2))
console.log(multply(1,2))